version: '3.8'

services:
  whitelabelairport:
    image: ghcr.io/pppwaw/white-label-airport-core
:latest
    network_mode: host
    environment:
      CONFIG: "https://github.com/pppwaw/white-label-airport/raw/refs/heads/main/test.configs/warp"
    volumes:
      - ./whitelabelairport.json:/whitelabelairport/whitelabelairport.json
    command: ["/opt/whitelabelairport.sh"]
